"""Generate the eye art header for the XIAO firmware (all styles).

For each style it emits, with the style's suffix:
  SOCKET_HALF_x  120x120 RGB565  fixed dark socket, doubled on the chip
  IRIS_ART_x     240x240 RGB565  iris disc + halo, moves with gaze
  LID_UP_x / LID_LO_x  eyelid art in lid space
  GLOW_R/G/B_x   additive glow by distance from the pupil edge
Shared by all styles: IRIS_SPAN_L/R (opaque iris span per row) and DIST_LUT.
Run:  python gen_assets.py ../eye_art.h
"""
import sys
import numpy as np
from PIL import Image
sys.path.insert(0, ".")
from render import (N, R, X, Y, xx, yy, SS, STYLES, IRIS_R, sample, smooth, ramp,
                    NOISE_A, NOISE_B, FIBER, crack_dist)
from gen_lids import lid, to565 as lid565, DEPTH as LID_DEPTH
from gen_membrane import membrane, to565 as memb565, SIZE as MEMB_SIZE
from sclera import sclera

BUILD = [("Classic Pumpkin", "PUMPKIN"), ("Ghostly Skeleton", "GHOST"),
         ("Bloodshot Human", "HUMAN")]

# Which lid set each style ships with. A skull has no skin, so the human eye
# gets dried tissue rather than the fresh-skin look.
LID_SETS = [("Ember rind", "EMBER", "Classic Pumpkin"),
            ("Pale bone", "BONE", "Ghostly Skeleton"),
            ("Dried flesh", "DRIED", "Dried flesh")]
LID_SET_FOR = {"Classic Pumpkin": 0, "Ghostly Skeleton": 1, "Bloodshot Human": 2}

def down(a):
    return a.reshape(240, SS, 240, SS, *a.shape[2:]).mean(axis=(1, 3))

def to565(rgb):
    return np.clip(np.round(rgb * [31, 63, 31]), 0, [31, 63, 31]).astype(np.uint16)

def pack(q):
    return (q[..., 0].astype(np.uint32) << 11) | (q[..., 1].astype(np.uint32) << 5) | q[..., 2]

def arr(name, ctype, vals, per=16):
    lines = ["  " + ", ".join(vals[i:i + per]) + "," for i in range(0, len(vals), per)]
    return f"const {ctype} {name}[{len(vals)}] PROGMEM = {{\n" + "\n".join(lines) + "\n};\n"

hexs = lambda a: [f"0x{v:04X}" for v in a.ravel()]
out = ["#pragma once\n// Generated by gen_assets.py. Do not edit by hand; regenerate instead.\n"
       "#include <stdint.h>\n#ifndef PROGMEM\n#define PROGMEM\n#endif\n\n",
       f"#define ART_GLOW_LEN 64\n#define ART_LID_DEPTH {LID_DEPTH}\n",
       f"#define ART_MEMB_SIZE {MEMB_SIZE}\n",
       "// Set SINGLE_STYLE_ONLY to 1 to build the first style only (halves build time).\n"
       "#ifndef SINGLE_STYLE_ONLY\n#define SINGLE_STYLE_ONLY 0\n#endif\n"
       f"#if SINGLE_STYLE_ONLY\n#define ART_STYLE_COUNT 1\n#else\n#define ART_STYLE_COUNT {len(BUILD)}\n#endif\n\n"]

r_disp = np.sqrt(X * X + Y * Y)
geom = []          # per style: (iris_px, pupil half width, half height, round radius, round default)

for style, sfx in BUILD:
    s = STYLES[style]
    iris_frac = s.get("iris_r", IRIS_R)
    IRIS_PX = 120 * iris_frac
    lx0, ly0 = X / iris_frac, Y / iris_frac
    r = np.sqrt(lx0 * lx0 + ly0 * ly0)
    th = np.arctan2(ly0, lx0)
    # ---- socket (half res) ----
    if s.get("sclera"):
        sock = sclera(iris_frac)
    else:
        sock = np.array(s["socket"], np.float32) * (0.55 + 0.9 * sample(NOISE_B, xx * .5, yy * .5)[..., None])
        sock *= (1 - smooth(0.75, 1.0, r_disp))[..., None]
        sock *= (r_disp < 1.0)[..., None]
    sock = down(sock).reshape(120, 2, 120, 2, 3).mean(axis=(1, 3))

    # ---- iris ----
    fib = sample(FIBER, (th / (2 * np.pi)) * 512 * 5, r * 25)
    fib = np.clip((fib - .5) * 1.6 + .5, 0, 1)
    fib2 = sample(NOISE_A, (th / (2 * np.pi)) * 512, r * 90)
    t = np.clip(r + (fib - .5) * .18, 0, 1)
    col = ramp(s["stops"], t) * (0.72 + 0.55 * fib)[..., None] * (0.85 + 0.3 * fib2)[..., None]
    if s["cracks"] > 0:
        wu = lx0 + (sample(NOISE_B, lx0 * 60 + 100, ly0 * 60 + 100) - .5) * .10
        wv = ly0 + (sample(NOISE_B, lx0 * 60 + 300, ly0 * 60 + 300) - .5) * .10
        d = crack_dist(wu, wv, s.get("cells", 80))
        width = 0.010 + 0.012 * sample(NOISE_A, lx0 * 80, ly0 * 80)
        crack = (1 - smooth(width * .4, width, d)) * smooth(.30, .50, r) * s["cracks"]
        glowc = np.exp(-d / 0.035) * smooth(.30, .5, r) * s["cracks"]
        col *= (1 + 0.35 * glowc)[..., None]
        col *= (1 - 0.92 * crack)[..., None]
    col *= (1 - 0.7 * smooth(.82, 1.0, r))[..., None]
    col = np.clip(col, 0, 1)

    iris_a = (r <= 1.0).astype(np.float32)
    halo = np.exp(-np.clip(r - 1, 0, None) / 0.12) * (1 - iris_a) * 0.35 * (r_disp < 2.0)
    if s.get("sclera"):
        halo = halo * 0.0            # nothing to add on top of a bright white
    layer = down(col * iris_a[..., None] + np.array(s["rim"], np.float32) * halo[..., None])
    alpha = down(iris_a)

    sock_q, lay_q = to565(sock), to565(layer)
    opaque = alpha >= 0.999
    smax = sock_q.reshape(-1, 3).max(axis=0)
    room = np.array([31, 63, 31]) - smax
    for c in range(3):
        ch = lay_q[..., c]
        ch[~opaque] = np.minimum(ch[~opaque], room[c])
    print(style, "socket max", smax)

    spanL, spanR = np.full(240, -1, int), np.full(240, -2, int)
    for y in range(240):
        xsr = np.where(opaque[y])[0]
        if len(xsr):
            spanL[y], spanR[y] = xsr.min(), xsr.max()
            assert len(xsr) == xsr.max() - xsr.min() + 1
    out.append(arr(f"IRIS_SPAN_L_{sfx}", "int16_t", [str(v) for v in spanL]))
    out.append(arr(f"IRIS_SPAN_R_{sfx}", "int16_t", [str(v) for v in spanR]))
    geom.append((IRIS_PX, 0.22 * IRIS_PX, 0.95 * IRIS_PX,
                 (0.42 if s.get("pupil") == "round" else 0.30) * IRIS_PX,
                 bool(s.get("round_default", False))))

    g = 0.55 * np.exp(-np.arange(64) / (0.14 * IRIS_PX))
    glow = np.clip(np.round(g[:, None] * np.array(s["hot"])[None, :] * 255), 0, 255).astype(int)

    if sfx == BUILD[1][1]:
        out.append("#if !SINGLE_STYLE_ONLY\n")
    out.append(f"// ---------------- {style} ----------------\n")
    out.append(arr(f"SOCKET_HALF_{sfx}", "uint16_t", hexs(pack(sock_q)), 12))
    # Palettised iris: 8-bit indices plus a 256-colour table. Half the size of
    # full colour, which is what lets it live in RAM next to Wi-Fi, and it makes
    # the colour trim instant (256 entries instead of 57,600 pixels).
    rgb8 = np.stack([(lay_q[..., 0] << 3) | (lay_q[..., 0] >> 2),
                     (lay_q[..., 1] << 2) | (lay_q[..., 1] >> 4),
                     (lay_q[..., 2] << 3) | (lay_q[..., 2] >> 2)], -1).astype(np.uint8)
    qim = Image.fromarray(rgb8).quantize(colors=256, method=Image.MEDIANCUT,
                                         dither=Image.Dither.FLOYDSTEINBERG)
    idx = np.array(qim, dtype=np.uint8)
    pg = qim.getpalette()[:768]
    pg = pg + [0] * (768 - len(pg))
    pal = np.array(pg, dtype=np.float32).reshape(256, 3) / 255.0
    pal565 = pack(to565(pal))
    err = np.abs(rgb8.astype(int) - np.array(qim.convert("RGB"), dtype=int)).mean()
    print(f"  {style}: palette error {err:.2f}/255 average")
    out.append(arr(f"IRIS_PAL_{sfx}", "uint16_t", hexs(pal565), 12))
    out.append(arr(f"IRIS_IDX_{sfx}", "uint8_t", [str(v) for v in idx.ravel()], 24))
    out.append(arr(f"MEMBRANE_{sfx}", "uint16_t", hexs(memb565(membrane(style, IRIS_PX))), 12))
    for i, c in enumerate("RGB"):
        out.append(arr(f"GLOW_{c}_{sfx}", "uint8_t", [str(v) for v in glow[:, i]]))
    Image.fromarray((np.clip(layer, 0, 1) * 255).astype(np.uint8)).save(f"layer_iris_{sfx.lower()}.png")

out.append("#endif  // !SINGLE_STYLE_ONLY  (shared tables below are always needed)\n\n")

# ---- eyelid sets, chosen independently of the eye style ----
out.append(f"#define ART_LID_SET_COUNT {len(LID_SETS)}\n")
for name, sfx, palette_key in LID_SETS:
    lu, ll = lid(True, palette_key), lid(False, palette_key)
    b8 = np.clip(np.round(np.concatenate([lu, ll], 0) * 255), 0, 255).astype(np.uint8)
    lq = Image.fromarray(b8).quantize(colors=256, method=Image.MEDIANCUT,
                                      dither=Image.Dither.FLOYDSTEINBERG)
    lidx = np.array(lq, dtype=np.uint8)
    lpg = lq.getpalette()[:768]
    lpg = lpg + [0] * (768 - len(lpg))
    lpal = np.array(lpg, dtype=np.float32).reshape(256, 3) / 255.0
    out.append(f"// ---------------- eyelids: {name} ----------------\n")
    out.append(arr(f"LID_PAL_{sfx}", "uint16_t", hexs(pack(to565(lpal))), 12))
    out.append(arr(f"LID_UP_{sfx}", "uint8_t", [str(v) for v in lidx[:LID_DEPTH].ravel()], 24))
    out.append(arr(f"LID_LO_{sfx}", "uint8_t", [str(v) for v in lidx[LID_DEPTH:].ravel()], 24))
out.append("struct LidSet {\n  const char *name;\n  const uint8_t *up;\n  const uint8_t *lo;\n"
           "  const uint16_t *pal;\n};\n")
out.append("const LidSet ART_LID_SETS[ART_LID_SET_COUNT] = {\n" +
           "\n".join(f'  {{ "{name}", LID_UP_{sfx}, LID_LO_{sfx}, LID_PAL_{sfx} }},'
                     for name, sfx, _ in LID_SETS) + "\n};\n")
a_, b_ = np.meshgrid(np.arange(64), np.arange(64))
dl = np.minimum(np.round(np.sqrt(a_ * a_ + b_ * b_)), 255).astype(int)
out.append("// DIST_LUT[b*64+a] = round(sqrt(a*a+b*b)), for the glow past the pupil tips\n")
out.append(arr("DIST_LUT", "uint8_t", [str(v) for v in dl.ravel()]))

# ---- style table ----
out.append("\nstruct ArtStyle {\n  const char *name;\n  const uint16_t *socket;\n  const uint8_t *irisIdx;\n  const uint16_t *irisPal;\n"
           "  uint8_t lidSet;\n  const uint16_t *membrane;\n"
           "  const uint8_t *glowR;\n  const uint8_t *glowG;\n  const uint8_t *glowB;\n"
           "  const int16_t *spanL;\n  const int16_t *spanR;\n"
           "  float irisRadiusPx;\n  float pupilHalfW;\n  float pupilHalfH;\n  float pupilRoundR;\n"
           "  bool roundPupilDefault;\n};\n")
rows = [(("" if i == 0 else "#if !SINGLE_STYLE_ONLY\n") +
         f'  {{ "{name}", SOCKET_HALF_{sfx}, IRIS_IDX_{sfx}, IRIS_PAL_{sfx}, {LID_SET_FOR[name]},'
        f' MEMBRANE_{sfx}, GLOW_R_{sfx}, GLOW_G_{sfx}, GLOW_B_{sfx},'
         f' IRIS_SPAN_L_{sfx}, IRIS_SPAN_R_{sfx},'
         f' {geom[i][0]:.2f}f, {geom[i][1]:.2f}f, {geom[i][2]:.2f}f, {geom[i][3]:.2f}f,'
         f' {"true" if geom[i][4] else "false"} }},' +
         ("" if i == 0 else "\n#endif")) for i, (name, sfx) in enumerate(BUILD)]
out.append("const ArtStyle ART_STYLES[ART_STYLE_COUNT] = {\n" + "\n".join(rows) + "\n};\n")
open(sys.argv[1] if len(sys.argv) > 1 else "eye_art.h", "w").write("".join(out))
print("written")
